# Generated by Django 5.2.5 on 2025-09-04 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_carrito_itemcarrito'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemcarrito',
            name='unique_carrito_producto',
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together={('carrito', 'producto')},
        ),
    ]
